
name: Terraform Apply

on:
  pull_request_review:
    types: [submitted]

env:
  TERRAFORM_VERSION: "1.7.4"

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
#    if: github.event.review.state == 'approved'
    steps:
      - uses: actions/checkout@v3

      - name: Get PR ID
        id: pr-id
        shell: bash
        env:
          GITHUB_REF: ${{ inputs.github_ref }}
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Terraform Apply
        uses: ./.github/apply
        with:
          terraform_directory: "."
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          github_token: ${{ secrets.TOKEN }}
          pr_id: ${{ steps.pr-id.outputs.PR_NUMBER }}
          role_arn: ${{ secrets.ROLE_ARN }}
          aws_region: ${{ secrets.REGION }}

