name: Deploy with terraform apply

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TERRAFORM_VERSION: 1.8.1
  TERRAFORM_DIR: .
  AWS_REGION: us-east-1
  TF_VAR_db_config: ${{ secrets.TF_VAR_DB_CONFIG }}
  TF_VAR_terraform_state_bucket: ${{ secrets.TF_VAR_TERRAFORM_STATE_BUCKET }}
  TF_VAR_vault_pass: ${{ secrets.TF_VAR_VAULT_PASS }}

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        working-directory: ${{ env.TERRAFORM_DIR }}
        shell: bash
        run: |
          terraform init

      - name: Terraform Apply
        id: apply
        working-directory: ${{ env.TERRAFORM_DIR }}
        shell: bash
        run: |
          terraform apply -auto-approve -input=false -no-color
